export const videoCallParamsDefault = {
   users: [],
   stream: null,
   receivingCall: false,
   caller: null,
   callerSignal: null,
   callAccepted: false,
   channel: null,
   peer1: null,
   peer2: null,
   isFocusMySelf: true,
   callPlaced: false,
   callPartner: null,
   mutedAudio: false,
   mutedScreenSharing: true,
   mutedCamera: true,
   cameraMode: 'user',
   statusCompanionMedia: { video: false, audio: false, screenSharing: false },
   statusMedia: { video: false, audio: false, screenSharing: false },
   hasVideo: false,
   hasAudio: false,
   screenStream: null,
   isConnect: false,
   partnerConnectIsLoading: false,
};
