export const videoCallParamsDefault = {
   users: [],
   stream: null,
   receivingCall: false,
   caller: null,
   callerSignal: null,
   callAccepted: false,
   channel: null,
   peer1: null,
   peer2: null,
   isFocusMySelf: true,
   callPlaced: false,
   callPartner: null,
   mutedAudio: false,
   mutedScreenSharing: false,
   mutedCamera: false,
   cameraMode: 'user',
   statusCompanionMedia: { video: false, audio: false },
   statusMedia: { video: false, audio: false },
};
